"""Visualization utilities for segmentation training metrics.

This module reads saved training history and generates a combined metric plot
for losses and validation mean IoU.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt

import config



def plot_training_curves(history_path: Path = config.HISTORY_PATH) -> Path:
    """Plot training and validation curves from history JSON.

    Args:
        history_path: Path to `history.json` generated by train.py.

    Returns:
        Path to the saved PNG plot.

    Raises:
        FileNotFoundError: If history JSON does not exist.
        ValueError: If required metric keys are missing.
    """
    if not history_path.exists():
        raise FileNotFoundError(f"History file not found: {history_path}")

    with history_path.open("r", encoding="utf-8") as f:
        history = json.load(f)

    required_keys = ["train_loss", "val_loss", "val_mean_iou"]
    missing_keys = [key for key in required_keys if key not in history]
    if missing_keys:
        raise ValueError(f"Missing required history keys: {missing_keys}")

    train_loss = history["train_loss"]
    val_loss = history["val_loss"]
    val_mean_iou = history["val_mean_iou"]

    epochs = list(range(1, len(train_loss) + 1))

    config.ensure_output_dirs()

    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Left subplot: Loss curves
    ax1.plot(epochs, train_loss, label="Train", color="#0078d4", linewidth=2.5)
    ax1.plot(epochs, val_loss, label="Val", color="#ff8c00", linewidth=2.5)
    ax1.set_title("Loss", fontsize=14, fontweight="bold")
    ax1.set_xlabel("Epoch", fontsize=12)
    ax1.set_ylabel("Loss", fontsize=12)
    ax1.grid(True, linestyle="--", alpha=0.3)
    ax1.legend(fontsize=11, loc="upper right")

    # Right subplot: Validation mIoU
    ax2.plot(epochs, val_mean_iou, label="Val mIoU", color="#0078d4", linewidth=2.5)
    ax2.set_title("Validation mIoU", fontsize=14, fontweight="bold")
    ax2.set_xlabel("Epoch", fontsize=12)
    ax2.set_ylabel("mIoU", fontsize=12)
    ax2.grid(True, linestyle="--", alpha=0.3)
    ax2.legend(fontsize=11, loc="lower right")

    plt.tight_layout()
    plt.savefig(config.CURVES_PATH, dpi=200, bbox_inches="tight")
    plt.close()

    print(f"Saved training curves to: {config.CURVES_PATH}")
    return config.CURVES_PATH



def main() -> None:
    """Entry point for plotting training curves."""
    plot_training_curves(config.HISTORY_PATH)


if __name__ == "__main__":
    main()
